---
title: "Lab 06 - Ugly charts and Simpson's paradox"
author: "Lily Botha"
date: "02/23/2026"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(dsbox)
library(mosaicData) 
```

### Exercise 1: Instructional staff employment trends

```{r read-data, message=FALSE}
staff <- read_csv("data/instructional-staff.csv")
```
```{r long-format, message=FALSE}
staff_long <- staff %>%
  pivot_longer(cols = -faculty_type, names_to = "year") %>%
  mutate(value = as.numeric(value))
staff_long
```

```{r line-graph}
staff_long %>%
  ggplot(aes(
    x = year,
    y = value,
    group = faculty_type,
    color = faculty_type
  )) +
  labs(
    title = "Trends in Instructional Staff Employment Status",
    x = "Year",
    y = "Percent of Total Instructional Staff",
    color = "Faculty Type"
  ) +
  geom_line()
```


### Exercise 2

Remove this text, and add your answer for Exercise 1 here.
Add code chunks as needed.
Don't forget to label your code chunk.
Do not use spaces in code chunk labels.

### Exercise 3

...

Add exercise headings as needed.
